version: "3.9"
services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 54320:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: payment_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./
    privileged: true
    restart: unless-stopped
    ports:
      - 7001:8000
    env_file:
      - .env
    command:  bash -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      python create_super_user.py $ADMIN_LOGIN $ADMIN_PASS &&
      gunicorn stripe_test.wsgi -b 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./www:/www


  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
      - 7000:80
    depends_on:
      - backend
    volumes:
      - ./www:/www

volumes:
  postgres_data:
